 
services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server
    networks:
      - asa-network

  asa-server:
    build: 
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server
    networks:
      - asa-network

  asa-server2:
    build: 
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server2
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge